# Generated by Django 4.0.5 on 2022-06-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0002_question_participants_alter_question_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-date_created']},
        ),
    ]
