# Generated by Django 4.0.5 on 2022-06-20 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='topic', to='stack.topic'),
        ),
    ]
