# Generated by Django 4.0.5 on 2022-06-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0007_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(choices=[('javascript', 'javascript'), ('Python', 'Python'), ('C++', 'C++'), ('C', 'C'), ('PHP', 'PHP')], max_length=40),
        ),
    ]
