# Generated by Django 4.0.5 on 2022-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stack', '0008_alter_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(choices=[('javascript', 'javascript'), ('Python', 'Python'), ('C++', 'C++'), ('C', 'C'), ('PHP', 'PHP')], max_length=40),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
